package main

import (
	"fmt"
	"strings"

	"agentsfs.ai/afs/internal/core"
)

const primeUsage = `usage: afs prime [path] [--budget N]`

// runPrime prints the session orientation pack. The pack is plain text meant to
// be injected into a session as-is, so nothing is added around it here — no
// header, no footer, no "generated by" line an agent would have to read past.
func runPrime(args []string) {
	budget := 0 // 0 → core's default (4000 estimated tokens)
	var pos []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		switch {
		case arg == "--budget":
			if i+1 >= len(args) {
				fail(fmt.Errorf("--budget needs a token estimate\n%s", primeUsage))
			}
			i++
			budget = mustBudget(args[i])
		case strings.HasPrefix(arg, "--budget="):
			budget = mustBudget(strings.TrimPrefix(arg, "--budget="))
		default:
			if strings.HasPrefix(arg, "-") {
				fail(fmt.Errorf("unknown flag %q\n%s", arg, primeUsage))
			}
			pos = append(pos, arg)
		}
	}
	if len(pos) > 1 {
		fail(fmt.Errorf("%s", primeUsage))
	}
	pack, err := core.Prime(instanceRoot(pos, 0), budget)
	if err != nil {
		fail(err)
	}
	fmt.Print(pack.Text)
}

// mustBudget parses a token budget. Zero and negative are rejected rather than
// quietly meaning "unlimited": a caller computing a budget that came out zero
// wants to hear about it, not receive the whole instance.
func mustBudget(raw string) int {
	n := 0
	if _, err := fmt.Sscanf(raw, "%d", &n); err != nil || n <= 0 {
		fail(fmt.Errorf("bad budget %q (want a positive token estimate)", raw))
	}
	return n
}
